--BW01
--2440005416 - Davin Valentino
--2401954905 - Fidelia Lavani
--2401955006 - Willy
--2440011513 - Vanessa Tjandra


DROP DATABASE [bEJibun]

CREATE DATABASE [bEJibun]
GO

USE [bEJibun]
GO

CREATE TABLE Customer(
	CustomerID CHAR(5) PRIMARY KEY CHECK(CustomerID LIKE 'CU[0-9][0-9][0-9]'),
	CustomerName VARCHAR(50) NOT NULL,
	CustomerGender CHAR(6) CHECK(CustomerGender IN ('Female','Male')) NOT NULL,
	CustomerPhone CHAR(12) NOT NULL,
	CustomerDOB DATE NOT NULL CHECK(CustomerDOB BETWEEN '1990-01-01' AND CONVERT(VARCHAR,GETDATE(),23))
) 
GO

CREATE TABLE Staff(
	StaffID CHAR(5) PRIMARY KEY CHECK(StaffID LIKE 'ST[0-9][0-9][0-9]'),
	StaffName VARCHAR(50) NOT NULL,
	StaffGender CHAR(6) CHECK(StaffGender IN ('Female','Male')) NOT NULL,
	StaffPhone CHAR(12) NOT NULL,
	StaffSalary INT CHECK(StaffSalary>0) NOT NULL
)
GO

CREATE TABLE SalesTransaction(
	TransactionID CHAR(5) PRIMARY KEY CHECK(TransactionID LIKE 'SA[0-9][0-9][0-9]'),
	CustomerID CHAR(5) FOREIGN KEY REFERENCES Customer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE,
	StaffID CHAR(5) FOREIGN KEY REFERENCES Staff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	SalesDate DATE NOT NULL
)
GO

CREATE TABLE Vendor(
	VendorID CHAR(5) PRIMARY KEY CHECK(VendorID LIKE 'VE[0-9][0-9][0-9]'),
	VendorName VARCHAR(50)NOT NULL,
	VendorPhone CHAR(12)NOT NULL,
	VendorAddress VARCHAR(50) NOT NULL CHECK(VendorAddress LIKE '% Street'),
	VendorEmail VARCHAR(50) NOT NULL CHECK(VendorEmail LIKE '%@%.com')
)
GO

CREATE TABLE ItemType(
	ItemTypeID CHAR(5) PRIMARY KEY CHECK(ItemTypeID LIKE 'IP[0-9][0-9][0-9]'),
	ItemTypeName VARCHAR(50) NOT NULL CHECK(LEN(ItemTypeName)>=4)
)
GO

CREATE TABLE Item(
	ItemID CHAR(5) PRIMARY KEY CHECK(ItemID LIKE 'IT[0-9][0-9][0-9]'),
	ItemTypeID CHAR(5) FOREIGN KEY REFERENCES ItemType(ItemTypeID) ON UPDATE CASCADE ON DELETE CASCADE,
	ItemName VARCHAR(50) NOT NULL,
	Price INT CHECK(Price>0) NOT NULL,
	MinPurchase INT NOT NULL
)
GO

CREATE TABLE SalesTransactionDetail(
	TransactionID CHAR(5) FOREIGN KEY REFERENCES SalesTransaction(TransactionID),
	ItemID CHAR(5) FOREIGN KEY REFERENCES Item(ItemID) ON UPDATE CASCADE ON DELETE CASCADE,
	SalesQty INT NOT NULL,
	PRIMARY KEY(TransactionID,ItemID)
)
GO

CREATE TABLE PurchaseTransaction(
	PurchaseID CHAR(5) PRIMARY KEY CHECK(PurchaseID LIKE 'PH[0-9][0-9][0-9]'),
	StaffID CHAR(5) FOREIGN KEY REFERENCES Staff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	VendorID CHAR(5) FOREIGN KEY REFERENCES Vendor(VendorID) ON UPDATE CASCADE ON DELETE CASCADE,
	PurchaseDate DATE NOT NULL,
	ArrivalDate DATE
)
GO

CREATE TABLE PurchaseTransactionDetail(
	PurchaseID CHAR(5) FOREIGN KEY REFERENCES PurchaseTransaction(PurchaseID) ON UPDATE CASCADE ON DELETE CASCADE,
	ItemID CHAR(5) FOREIGN KEY REFERENCES Item(ItemID) ON UPDATE CASCADE ON DELETE CASCADE,
	PurchaseQty INT NOT NULL
	PRIMARY KEY(PurchaseID,ItemID)
)
GO